export const projects = [
  {
    title: 'HNC Real-Estate',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: '/images/1.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/peekaycee/homes.n.codes',
    visit: 'https://homes-n-codes.netlify.app',
    id: 0,
  },
  {
    title: 'HEMA Website',
    description:"This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: '/images/2.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/peekaycee/Hem-website',
    visit: 'https:hem.com',
    id: 1,
  },
  {
    title: 'EventSphere',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: '/images/3.png',
    tags: ['React', 'WebRTC'],
    source: 'https://github.com/peekaycee/event-details-website',
    visit: 'https://event-booking.com',
    id: 2,
  },
  {
    title: 'Coded Bar',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application that functions well and completes tasks.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/peekaycee/Coded-Bar',
    visit: 'https://https://codedbar.netlify.app/',
    id: 3,
  },
  {
    title: 'Barb Shoe Store',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application that functions well and completes tasks.",
    image: '/images/5.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/peekaycee/barb-shoe-store',
    visit: 'https://barb-shoe-app.netlify.app/',
    id: 4,
  },
  {
    title: 'Campus Navigate',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application that functions well and completes tasks.",
    image: '/images/6.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/peekaycee/campus-navigate',
    visit: 'https://campus-navigate.netlify.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Started my journey in Data Analytics in Python', },
  { year: 2022, text: 'Certified with Google Professional Data Analytics', },
  { year: 2023, text: 'Transited into front-end web development', },
  { year: 2024, text: 'Delved into full-stack and worked freelance', },
  { year: 2025, text: 'Internship and freelancing for Businesses', },
];