export const projects = [
  {
    title: 'HNC Real-Estate',
    description: "This is a real estate website for HNC Properties. In this platform, you can explore, buy, and rent premium homes, apartments, and commercial spaces with ease.",
    image: '/images/1.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/peekaycee/homes.n.codes',
    visit: 'https://homes-n-codes.netlify.app',
    id: 0,
  },
  {
    title: 'HEMA Website',
    description:"This is a church website for HEMA. On this website, you can connect with our ministry, join worship services, access inspiring sermons, and grow spiritually.",
    image: '/images/2.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/peekaycee/Hem-website',
    visit: 'https:hem.com',
    id: 1,
  },
  {
    title: 'EventSphere',
    description: "This is an event booking website for EventSphere. On this platform, you can discover, book, and manage tickets for concerts, conferences, weddings, and social events.",
    image: '/images/3.png',
    tags: ['React', 'WebRTC'],
    source: 'https://github.com/peekaycee/event-details-website',
    visit: 'https://event-booking.com',
    id: 2,
  },
  {
    title: 'BF Smoothies',
    description: "This is a smoothies outlet website for Beyond Fabs Smoothies. On this platform, you can explore healthy smoothies, order fresh blends online, and enjoy nutritious drinks delivered.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/peekaycee/Coded-Bar',
    visit: 'https://https://codedbar.netlify.app/',
    id: 3,
  },
  {
    title: 'Barb Shoe Store',
    description: "This is a shoe e-commerce website for Barb Shoe Store. On this platform, you can shop stylish footwear, browse trendy collections, and buy quality shoes online with ease.",
    image: '/images/5.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/peekaycee/barb-shoe-store',
    visit: 'https://barb-shoe-app.netlify.app/',
    id: 4,
  },
  {
    title: 'Campus Navigate',
    description: "This is a campus navigation website called Campus Navigate. In this web-app, you can explore UNILAG routes, find buildings, optimize paths, and query data using GraphQL.",
    image: '/images/6.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/peekaycee/campus-navigate',
    visit: 'https://campus-navigate.netlify.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Started my journey in Data Analytics in Python', },
  { year: 2022, text: 'Certified with Google Professional Data Analytics', },
  { year: 2023, text: 'Transited into front-end web development', },
  { year: 2024, text: 'Delved into full-stack and worked freelance', },
  { year: 2025, text: 'Internship and freelancing for Businesses', },
];